/**
 * Turns the vendored Google myanmar-tools assets into plain TypeScript modules.
 *
 * The upstream npm package ships `index.js` pointing at a `build_node/` directory that
 * isn't in the tarball, so `require('myanmar-tools')` throws. Rather than depend on it,
 * we vendor the two pieces that matter, the trained Markov model and the
 * transliteration rule tables, and generate importable modules from them here.
 *
 * Run via `npm run build:model`. Regenerate whenever the .dat or rule tables change.
 */
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { runInNewContext } from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const vendor = join(root, 'src', 'vendor');

// Both packages are generated here. The Python package reads its own copy at import
// time rather than reaching across the repo, so it needs the files written into its
// package directory, not just into shared/.
const RULE_OUTPUTS = [
  join(root, 'shared', 'rules'),
  join(root, 'python', 'src', 'jawgyi', 'data', 'rules'),
];
const MODEL_OUTPUTS = [
  join(root, 'shared'),
  join(root, 'python', 'src', 'jawgyi', 'data'),
];

const HEADER = `// GENERATED BY scripts/build-vendor.mjs. DO NOT EDIT BY HAND.
// Derived from Google's myanmar-tools (Apache-2.0). See NOTICE.
`;

// The Markov model
// 28KB binary -> ~37KB of base64. Embedding it keeps the package dependency-free
// and avoids a filesystem read, which matters for browser and edge runtimes.
const dat = readFileSync(join(vendor, 'zawgyiUnicodeModel.dat'));
writeFileSync(
  join(vendor, 'model-data.ts'),
  `${HEADER}
/** Base64 of zawgyiUnicodeModel.dat (${dat.length} bytes). */
export const MODEL_BASE64 =
  '${dat.toString('base64')}';
`,
);

// The transliteration rule tables
// Each upstream file declares one function returning an array of phases, each phase
// an array of {p: RegExp, s: string}. We evaluate it in a throwaway context and
// re-emit the regex *sources*, so the generated module has no eval at runtime.
for (const [file, fn] of [
  ['Z2U', 'getAllRulesZ2U'],
  ['U2Z', 'getAllRulesU2Z'],
  ['ZNorm', 'getAllRulesZNorm'],
]) {
  const src = readFileSync(join(vendor, 'translit', `${file}.js`), 'utf8');
  const sandbox = {};
  runInNewContext(`${src};\nresult = ${fn}();`, sandbox);

  const phases = sandbox.result.map((phase) =>
    phase.map((rule) => {
      // Upstream anchors every pattern with '^' and walks the string by hand.
      // Keep the source verbatim; runPhase depends on the anchor.
      const entry = { p: rule.p.source, s: rule.s };
      // Upstream writes the string 'true' here, and runPhase only ever tests the field
      // for null. Presence is the real semantic. Normalise to a boolean so the
      // generated types are honest; behaviour is identical because null-ness is unchanged.
      if (rule.matchOnStart != null) entry.matchOnStart = true;
      if (rule.revisit != null) entry.revisit = rule.revisit;
      return entry;
    }),
  );

  const count = phases.reduce((n, p) => n + p.length, 0);

  // The Python port consumes the same tables. Emitting JSON keeps the two
  // implementations sharing data rather than each carrying its own transcription,
  // which is the only way they stay in agreement as the rules change.
  const json = JSON.stringify(phases);
  for (const dir of RULE_OUTPUTS) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, `${file.toLowerCase()}.json`), json);
  }

  writeFileSync(
    join(vendor, 'translit', `${file.toLowerCase()}.ts`),
    `${HEADER}import type { RawRule } from '../translit.ts';

/** ${phases.length} phases, ${count} rules. */
export const ${file.toUpperCase()}_RULES: readonly (readonly RawRule[])[] = ${escapeNonAscii(
      JSON.stringify(phases, null, 2),
    )};
`,
  );
  console.log(`${file}: ${phases.length} phases, ${count} rules`);
}

/** Emit non-ASCII as \\uXXXX so the generated files stay diffable and encoding-proof. */
function escapeNonAscii(s) {
  return s.replace(/[\u0080-￿]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
}

console.log(`model: ${dat.length} bytes -> ${dat.toString('base64').length} base64 chars`);

// The trained model is shared verbatim by both implementations.
for (const dir of MODEL_OUTPUTS) {
  mkdirSync(dir, { recursive: true });
  copyFileSync(join(vendor, 'zawgyiUnicodeModel.dat'), join(dir, 'zawgyiUnicodeModel.dat'));
}
console.log('shared/ and python/src/jawgyi/data/ updated');
